title: honey kitty
email: hello@honeykitty.com.au

tagline: 

description: |
  honeykitty
baseurl: ""
url: "https://honeykitty.com.au"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed
  sass_dir: _sass

page_excerpts: true
excerpt_separator: <!--more-->
permalink: /:slugified_categories/:slug/

